import React from "react";

import image1 from "./assets/images/3.jpg";
import image2 from "./assets/images/4.jpeg";
import image3 from "./assets/images/5.jpeg";
import image4 from "./assets/images/6.jpeg";
import image5 from "./assets/images/7.jpeg";
import image6 from "./assets/images/8.jpg";
import image7 from "./assets/images/9.jpg";
import image8 from "./assets/images/10.jpeg";
import image9 from "./assets/images/11.jpg";
import image10 from "./assets/images/12.jpg";
import image11 from "./assets/images/13.jpeg";
import image12 from "./assets/images/14.jpeg";
import image13 from "./assets/images/15.jpg";
import image14 from "./assets/images/16.jpeg";
import image15 from "./assets/images/17.jpg";
import image16 from "./assets/images/18.jpg";
import image17 from "./assets/images/19.jpg";
import image18 from "./assets/images/20.jpg";
import image19 from "./assets/images/21.jpg";
import image20 from "./assets/images/22.jpeg";
import image21 from "./assets/images/11.jpg";
import image22 from "./assets/images/12.jpg";
import image23 from "./assets/images/8.jpg";
import image24 from "./assets/images/9.jpg";
import image25 from "./assets/images/18.jpg";
const products = [
  {
    id: 1,
    title: "Modern Poster",
    price: "30.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Liddy",
    category: 1,
    image: image1,
    color: "black",
  },
  {
    id: 2,
    title: "Bar Stool",
    price: "40.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecoM2MyHJGHLVi5l",
    brand: "Liddy",
    category: 1,
    image: image2,
    color: "black",
  },
  {
    id: 3,
    title: "Armchair",
    price: "125.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recd1jIVIEChmiwhe",
    brand: "Marcos",
    category: 1,
    image: image3,
    color: "green",
  },
  {
    id: 4,
    title: "Suede Armchair",
    price: "159.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecroK1VD8qVdMP5H",
    brand: "Caressa",
    category: 2,
    image: image4,
  },
  {
    id: 5,
    title: "Shelf",
    price: "309.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Rec7CjDWKRgNQtrKe",
    brand: "Ikea",
    category: 2,
    image: image5,
    color: "bleu",
  },
  {
    id: 6,
    title: "Modern Bookshelf",
    price: "309.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecoAJYUCuEKxcPSr",
    brand: "Caressa",
    category: 2,
    image: image6,
  },
  {
    id: 7,
    title: "High-Back Bench",
    price: "309.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recrfxv3EwpvJwvjq",
    brand: "Ikea",
    category: 4,
    image: image7,
    color: "green",
  },
  {
    id: 8,
    title: "Wooden Desk",
    price: "600.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recm7wC8TBVdU9oEL",
    brand: "Ikea",
    category: 4,
    image: image8,
    color: "bleu",
  },
  {
    id: 9,
    title: "Dining Table",
    price: "621.93",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recm7wC8TBVdU9oEL",
    brand: "Ikea",
    category: 4,
    image: image9,
    color: "black",
  },
  {
    id: 10,
    title: "Lits deux place",
    price: "621.93",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recm7wC8TBVdU9oEL",
    brand: "Ikea",
    category: 6,
    image: image10,
    color: "green",
  },
  {
    id: 11,
    title: "Fauteuille",
    price: "30.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecQ0fMd8T0Vk211E",
    brand: "Liddy",
    category: 5,
    image: image11,
    color: "red",
  },
  {
    id: 12,
    title: "Chaise",
    price: "40.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecoM2MyHJGHLVi5l",
    brand: "Liddy",
    category: 6,
    image: image12,
    color: "red",
  },
  {
    id: 13,
    title: "Table bureau",
    price: "125.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recd1jIVIEChmiwhe",
    brand: "Marcos",
    category: 3,
    image: image13,
    color: "red",
  },
  {
    id: 14,
    title: "Equipement meuble",
    price: "159.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecroK1VD8qVdMP5H",
    brand: "Caressa",
    category: 4,
    image: image14,
    color: "red",
  },
  {
    id: 15,
    title: "Canape",
    price: "309.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Rec7CjDWKRgNQtrKe",
    brand: "Ikea",
    category: 2,
    image: image15,
    color: "black",
  },
  {
    id: 16,
    title: "Poof",
    price: "309.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "RecoAJYUCuEKxcPSr",
    brand: "Caressa",
    category: 5,
    image: image16,
    color: "bleu",
  },
  {
    id: 17,
    title: "coiffeuse coffret",
    price: "309.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recrfxv3EwpvJwvjq",
    brand: "Ikea",
    category: 1,
    image: image17,
  },
  {
    id: 18,
    title: "coiffeuse xxl",
    price: "600.99",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recm7wC8TBVdU9oEL",
    brand: "Ikea",
    category: 6,
    image: image18,
    color: "bleu",
  },
  {
    id: 19,
    title: "Table cuisine",
    price: "621.93",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recm7wC8TBVdU9oEL",
    brand: "Ikea",
    category: 4,
    image: image19,
    color: "green",
  },
  {
    id: 20,
    title: "table de nuit",
    price: "621.93",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recm7wC8TBVdU9oEL",
    brand: "Ikea",
    category: 6,
    image: image20,
    color: "green",
  },
  {
    id: 21,
    title: "Chambre couche",
    price: "621.93",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recm7wC8TBVdU9oEL",
    brand: "Ikea",
    category: 1,
    image: image21,
    color: "green",
  },
  {
    id: 22,
    title: "Dressing",
    price: "621.93",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recm7wC8TBVdU9oEL",
    brand: "Ikea",
    category: 6,
    image: image22,
    color: "black",
  },
  {
    id: 23,
    title: "Lits ",
    price: "621.93",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recm7wC8TBVdU9oEL",
    brand: "Ikea",
    category: 6,
    image: image23,
    color: "red",
  },
  {
    id: 24,
    title: "Commode",
    price: "621.93",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recm7wC8TBVdU9oEL",
    brand: "Ikea",
    category: 6,
    image: image24,
    color: "red",
  },
  {
    id: 25,
    title: "Meuble de chambre",
    price: "621.93",
    desc: "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "In Stock",
    sku: "Recm7wC8TBVdU9oEL",
    brand: "Marcos",
    category: 6,
    image: image25,
    color: "red",
  },
];
export default products;
